<a href="https://colab.research.google.com/github/2303a51729Ajaykumar/AIML-2025/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

List vs numpy


In [1]:
import numpy as np

In [2]:
from time import process_time
python_list=[i for i in range(10000)]
start=process_time()
python_list=[i+5 for i in python_list]
end=process_time()
print(end-start)

0.000917075000000267


In [4]:
np_array=np.array([i for i in range(10000)])
start=process_time()
np_array+=5
end=process_time()
print(end-start)

0.0012626909999990943


list

In [5]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array=np.array([1,1,2,3,4])
print(np_array)
type(np_array)

[1 1 2 3 4]


numpy.ndarray

In [7]:
print(np_array.shape)

(5,)


In [9]:
np=np.array([(1,2,3,4),(1,2,3,4)])
print(np.shape)

(2, 4)
(2, 4)


initial placeholder in numpy arrays

In [15]:
import numpy as np

In [16]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
y=np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
z=np.full((4,5),9)
print(z)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [19]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
b=np.random.random((3,4))
print(b)

[[0.34400391 0.40673512 0.32499516 0.44739884]
 [0.99231259 0.80929766 0.95724823 0.05209092]
 [0.03872489 0.19553489 0.8271525  0.84946141]]


In [21]:
c=np.random.randint(1,10,(3,4))
print(c)

[[1 1 1 3]
 [2 7 1 1]
 [5 3 8 4]]


In [23]:
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [24]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [25]:
# converting list to numpy array
list1=[1,2,3,4]
np_array=np.asarray(list1)
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

Anaylsising the array


In [27]:
f=np.random.randint(10,90,(2,3))
print(f)

[[81 15 20]
 [75 14 58]]
[[13 69 38]
 [10 34 33]]


In [28]:
print(f.ndim)

2


In [29]:
print(f.size)
print(f.dtype)

6
int64


Mathematical operation on a  numpy array

In [30]:
list1=[1,2,3,4]
list2=[5,6,7,8]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [31]:
a=np.random.randint(0,10,(3,4))
b=np.random.randint(10,30,(3,4))

In [32]:
print(a)
print(b)

[[5 1 1 1]
 [2 4 7 6]
 [1 2 0 7]]
[[26 16 18 20]
 [19 14 26 17]
 [13 24 11 20]]


In [33]:
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[[31 17 19 21]
 [21 18 33 23]
 [14 26 11 27]]
[[-21 -15 -17 -19]
 [-17 -10 -19 -11]
 [-12 -22 -11 -13]]
[[0.19230769 0.0625     0.05555556 0.05      ]
 [0.10526316 0.28571429 0.26923077 0.35294118]
 [0.07692308 0.08333333 0.         0.35      ]]
[[130  16  18  20]
 [ 38  56 182 102]
 [ 13  48   0 140]]


In [36]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,30,(3,3))